package talive_test

import (
	"reflect"
	"testing"

	"github.com/MoroZvlg/talive"
)

// NOTE: The CSV fixtures consumed by these tests (test_data/pivot_hl/output_*.csv)
// were generated by a Python script using pandas to compute reference pivot levels from input_data2.csv.

func TestPivotHLDefault(t *testing.T) {
	candles, _ := readCandles("test_data/input_data2.csv")
	expected, _ := readData("test_data/pivot_hl/output_default.csv", []int{1, 2, 3}, 4)
	indicator, _ := talive.NewPivotHL(10, 10)
	result := make([][]float64, 3)
	for i := range result {
		result[i] = make([]float64, len(candles))
	}
	for i, candle := range candles {
		res := indicator.Next(candle)
		for j := 0; j < 3; j++ {
			result[j][i] = roundFloat(res[j], 4)
		}
	}
	labels := []string{"PivotHigh", "PivotLow", "Event"}
	for j, label := range labels {
		if !reflect.DeepEqual(result[j], expected[j]) {
			t.Fatalf("[PivotHL 10/10] %s mismatch %v", label, difference(result[j], expected[j]))
		}
	}
}

func TestPivotHLMin(t *testing.T) {
	candles, _ := readCandles("test_data/input_data2.csv")
	expected, _ := readData("test_data/pivot_hl/output_min.csv", []int{1, 2, 3}, 4)
	indicator, _ := talive.NewPivotHL(1, 1)
	result := make([][]float64, 3)
	for i := range result {
		result[i] = make([]float64, len(candles))
	}
	for i, candle := range candles {
		res := indicator.Next(candle)
		for j := 0; j < 3; j++ {
			result[j][i] = roundFloat(res[j], 4)
		}
	}
	labels := []string{"PivotHigh", "PivotLow", "Event"}
	for j, label := range labels {
		if !reflect.DeepEqual(result[j], expected[j]) {
			t.Fatalf("[PivotHL 1/1] %s mismatch %v", label, difference(result[j], expected[j]))
		}
	}
}

func TestPivotHLConstructorValidation(t *testing.T) {
	if _, err := talive.NewPivotHL(0, 5); err == nil {
		t.Fatal("expected error for leftBars=0")
	}
	if _, err := talive.NewPivotHL(5, 0); err == nil {
		t.Fatal("expected error for rightBars=0")
	}
	if _, err := talive.NewPivotHL(-1, 5); err == nil {
		t.Fatal("expected error for leftBars<0")
	}
}

func TestPivotHLSyntheticSmoke(t *testing.T) {
	// Highs: 1 2 3 4 5 4 3 2 1  -> pivot HIGH at index 4 (value 5), confirmed at index 8.
	// Lows:  9 8 7 6 5 6 7 8 9  -> pivot LOW  at index 4 (value 5), confirmed at index 8.
	feed := []*testCandle{
		{high: 1, low: 9},
		{high: 2, low: 8},
		{high: 3, low: 7},
		{high: 4, low: 6},
		{high: 5, low: 5},
		{high: 4, low: 6},
		{high: 3, low: 7},
		{high: 2, low: 8},
		{high: 1, low: 9},
	}
	indicator, _ := talive.NewPivotHL(4, 4)
	var events []float64
	var lastH, lastL float64
	for _, c := range feed {
		out := indicator.Next(c)
		events = append(events, out[2])
		lastH, lastL = out[0], out[1]
	}
	// Eight bars produce no event; the ninth confirms both a high and a low.
	// Tie-break rule says +1 wins, so we expect a single +1 at the last bar.
	wantEvents := []float64{0, 0, 0, 0, 0, 0, 0, 0, 1}
	if !reflect.DeepEqual(events, wantEvents) {
		t.Fatalf("event stream = %v, want %v", events, wantEvents)
	}
	if lastH != 5 || lastL != 5 {
		t.Fatalf("locked H/L = %v/%v, want 5/5", lastH, lastL)
	}
}

func TestPivotHLAsymmetric(t *testing.T) {
	// rightHigh=2, rightLow=3. Confirmation bars differ, so the high locks
	// strictly before the low — proves the per-side configuration works.
	feed := []*testCandle{
		{high: 1, low: 9},
		{high: 2, low: 8},
		{high: 5, low: 5}, // candidate pivot index 2
		{high: 3, low: 7},
		{high: 2, low: 8}, // bar 4 -> high pivot at idx 2 confirms (rightHigh=2)
		{high: 1, low: 9}, // bar 5 -> low pivot at idx 2 confirms (rightLow=3)
	}
	indicator, _ := talive.NewPivotHL(2, 2)
	indicator.WithAsymmetric(2, 2, 2, 3)
	var events []float64
	for _, c := range feed {
		events = append(events, indicator.Next(c)[2])
	}
	wantEvents := []float64{0, 0, 0, 0, 1, -1}
	if !reflect.DeepEqual(events, wantEvents) {
		t.Fatalf("asymmetric event stream = %v, want %v", events, wantEvents)
	}
}

func TestPivotHLIdle(t *testing.T) {
	// Strict-greater requirement: equal neighbors disqualify, so a flat series
	// produces NO pivots and the indicator stays idle forever.
	indicator, _ := talive.NewPivotHL(2, 2)
	for i := 0; i < 20; i++ {
		indicator.Next(&testCandle{high: 10, low: 5})
		if !indicator.IsIdle() {
			t.Fatalf("indicator should remain idle on flat data (bar %d)", i)
		}
	}
	// One spike that is strictly higher than its neighbors must clear idle.
	feed := []*testCandle{
		{high: 10, low: 5},
		{high: 10, low: 5},
		{high: 11, low: 4},
		{high: 10, low: 5},
		{high: 10, low: 5},
	}
	ind2, _ := talive.NewPivotHL(2, 2)
	for _, c := range feed {
		ind2.Next(c)
	}
	if ind2.IsIdle() {
		t.Fatal("indicator should exit idle after a strict spike")
	}
	if !ind2.IsWarmedUp() {
		t.Fatal("indicator should be warmed up after exiting idle")
	}
}

func TestPivotHLCurrentVal(t *testing.T) {
	candles, _ := readCandles("test_data/input_data2.csv")
	expected, _ := readData("test_data/pivot_hl/output_default.csv", []int{1, 2, 3}, 8)
	indicator, _ := talive.NewPivotHL(10, 10)
	for i := 0; i < 30; i++ {
		indicator.Next(candles[i])
	}
	currResult := indicator.Current(candles[30])
	labels := []string{"PivotHigh", "PivotLow", "Event"}
	for j, label := range labels {
		got := roundFloat(currResult[j], 8)
		want := roundFloat(expected[j][30], 8)
		if got != want {
			t.Fatalf("[PivotHL] wrong Current %s = %f, expected %f", label, got, want)
		}
	}
	// Next on the same candle must reproduce the Current output exactly.
	nextResult := indicator.Next(candles[30])
	for j, label := range labels {
		got := roundFloat(nextResult[j], 8)
		want := roundFloat(expected[j][30], 8)
		if got != want {
			t.Fatalf("[PivotHL] Current broke Next %s = %f, expected %f", label, got, want)
		}
	}
}

func TestPivotHLCurrentDoesNotMutate(t *testing.T) {
	candles, _ := readCandles("test_data/input_data2.csv")
	// Feed past several pivots so internal state is non-trivial.
	a, _ := talive.NewPivotHL(10, 10)
	b, _ := talive.NewPivotHL(10, 10)
	for i := 0; i < 200; i++ {
		a.Next(candles[i])
		b.Next(candles[i])
	}
	// Repeated Current calls on `a` must not perturb its state vs. untouched `b`.
	for i := 200; i < 220; i++ {
		_ = a.Current(candles[i])
		_ = a.Current(candles[i])
	}
	for i := 200; i < 220; i++ {
		ra := a.Next(candles[i])
		rb := b.Next(candles[i])
		for j := 0; j < 3; j++ {
			if ra[j] != rb[j] {
				t.Fatalf("Current mutated state: bar %d col %d  Current-poisoned=%v clean=%v",
					i, j, ra[j], rb[j])
			}
		}
	}
}

func Benchmark_PivotHL_Init_Allocations(b *testing.B) {
	b.Run("PivotHL(10,10)", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			benchSink, _ = talive.NewPivotHL(10, 10)
		}
	})
	b.Run("PivotHL(1,1)", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			benchSink, _ = talive.NewPivotHL(1, 1)
		}
	})
}

func Benchmark_PivotHL_Next_Allocations(b *testing.B) {
	candles, _ := readCandles("test_data/input_data2.csv")
	dataLen := len(candles)
	b.Run("PivotHL(10,10)", func(b *testing.B) {
		indicator, _ := talive.NewPivotHL(10, 10)
		dataIndex := 0
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			dataIndex = limitedDataIndex(dataIndex, dataLen)
			sliceDummy = indicator.Next(candles[dataIndex])
		}
	})
	b.Run("PivotHL(1,1)", func(b *testing.B) {
		indicator, _ := talive.NewPivotHL(1, 1)
		dataIndex := 0
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			dataIndex = limitedDataIndex(dataIndex, dataLen)
			sliceDummy = indicator.Next(candles[dataIndex])
		}
	})
}

func Benchmark_PivotHL_Current_Allocations(b *testing.B) {
	candles, _ := readCandles("test_data/input_data2.csv")
	dataLen := len(candles)
	b.Run("PivotHL(10,10)", func(b *testing.B) {
		indicator, _ := talive.NewPivotHL(10, 10)
		dataIndex := primeForCurrentBench(indicator, candles)
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			dataIndex = limitedDataIndex(dataIndex, dataLen)
			sliceDummy = indicator.Current(candles[dataIndex])
		}
	})
}
