package talive_test

import (
	"reflect"
	"slices"
	"testing"
	"time"

	"github.com/MoroZvlg/talive"
)

func cloneFloats(values []float64) []float64 {
	return slices.Clone(values)
}

// NOTE: The CSV fixtures consumed by these tests (test_data/pivot_points/output_*.csv)
// were generated by a Python script using pandas to compute reference pivot levels from input_data2.csv.

func TestPivotPointsStandardDailyDefault(t *testing.T) {
	candles, _ := readCandles("test_data/input_data2.csv")
	expectedParsedData, _ := readData("test_data/pivot_points/output_standard_daily.csv", []int{1, 2, 3, 4, 5, 6, 7}, 4)
	indicator, _ := talive.NewPivotPoints()
	result := make([][]float64, 7)
	for i := range result {
		result[i] = make([]float64, len(candles))
	}
	for i, candle := range candles {
		res := indicator.Next(candle)
		for j := 0; j < 7; j++ {
			result[j][i] = roundFloat(res[j], 4)
		}
	}
	labels := []string{"P", "R1", "R2", "R3", "S1", "S2", "S3"}
	for j, label := range labels {
		if !reflect.DeepEqual(result[j], expectedParsedData[j]) {
			t.Fatalf("[PivotPoints Standard/Daily] %s values didn't match %v", label, difference(result[j], expectedParsedData[j]))
		}
	}
}

func TestPivotPointsFibonacciWeekly(t *testing.T) {
	candles, _ := readCandles("test_data/input_data2.csv")
	expectedParsedData, _ := readData("test_data/pivot_points/output_fibonacci_weekly.csv", []int{1, 2, 3, 4, 5, 6, 7}, 4)
	indicator, _ := talive.NewPivotPoints()
	indicator.WithAnchor(talive.AnchorWeekly).WithType(talive.PivotFibonacci)
	result := make([][]float64, 7)
	for i := range result {
		result[i] = make([]float64, len(candles))
	}
	for i, candle := range candles {
		res := indicator.Next(candle)
		for j := 0; j < 7; j++ {
			result[j][i] = roundFloat(res[j], 4)
		}
	}
	labels := []string{"P", "R1", "R2", "R3", "S1", "S2", "S3"}
	for j, label := range labels {
		if !reflect.DeepEqual(result[j], expectedParsedData[j]) {
			t.Fatalf("[PivotPoints Fibonacci/Weekly] %s values didn't match %v", label, difference(result[j], expectedParsedData[j]))
		}
	}
}

func TestPivotPointsCamarillaMonthly(t *testing.T) {
	candles, _ := readCandles("test_data/input_data2.csv")
	expectedParsedData, _ := readData("test_data/pivot_points/output_camarilla_monthly.csv", []int{1, 2, 3, 4, 5, 6, 7, 8, 9}, 4)
	indicator, _ := talive.NewPivotPoints()
	indicator.WithAnchor(talive.AnchorMonthly).WithType(talive.PivotCamarilla)
	result := make([][]float64, 9)
	for i := range result {
		result[i] = make([]float64, len(candles))
	}
	for i, candle := range candles {
		res := indicator.Next(candle)
		for j := 0; j < 9; j++ {
			result[j][i] = roundFloat(res[j], 4)
		}
	}
	labels := []string{"P", "R1", "R2", "R3", "R4", "S1", "S2", "S3", "S4"}
	for j, label := range labels {
		if !reflect.DeepEqual(result[j], expectedParsedData[j]) {
			t.Fatalf("[PivotPoints Camarilla/Monthly] %s values didn't match %v", label, difference(result[j], expectedParsedData[j]))
		}
	}
}

func TestPivotPointsIdle(t *testing.T) {
	indicator, _ := talive.NewPivotPoints()
	indicator.WithAnchor(talive.AnchorDaily)

	feed := []*testCandle{
		{high: 10, low: 5, close: 7, timestamp: time.Date(2026, 5, 1, 10, 0, 0, 0, time.UTC)},
		{high: 12, low: 4, close: 11, timestamp: time.Date(2026, 5, 1, 11, 0, 0, 0, time.UTC)},
		{high: 14, low: 9, close: 13, timestamp: time.Date(2026, 5, 2, 10, 0, 0, 0, time.UTC)},
		{high: 15, low: 8, close: 12, timestamp: time.Date(2026, 5, 2, 11, 0, 0, 0, time.UTC)},
	}
	var result []string
	for _, c := range feed {
		indicator.Next(c)
		if indicator.IsIdle() {
			result = append(result, "true")
		} else {
			result = append(result, "false")
		}
	}
	if !reflect.DeepEqual(result, []string{"true", "true", "false", "false"}) {
		t.Fatalf("[PivotPoints] wrong idle pattern %v", result)
	}
}

func TestPivotPointsCurrentVal(t *testing.T) {
	candles, _ := readCandles("test_data/input_data2.csv")
	expectedParsedData, _ := readData("test_data/pivot_points/output_standard_daily.csv", []int{1, 2, 3, 4, 5, 6, 7}, 8)
	indicator, _ := talive.NewPivotPoints()
	for i := 0; i < 22; i++ {
		indicator.Next(candles[i])
	}
	currResult := indicator.Current(candles[22])
	labels := []string{"P", "R1", "R2", "R3", "S1", "S2", "S3"}
	for j, label := range labels {
		got := roundFloat(currResult[j], 8)
		want := roundFloat(expectedParsedData[j][22], 8)
		if got != want {
			t.Fatalf("[PivotPoints] wrong Current %s value %f, expected %f", label, got, want)
		}
	}
	nextResult := indicator.Next(candles[22])
	for j, label := range labels {
		got := roundFloat(nextResult[j], 8)
		want := roundFloat(expectedParsedData[j][22], 8)
		if got != want {
			t.Fatalf("[PivotPoints] Current %s call broke Next %s value %f, expected %f", label, label, got, want)
		}
	}
}

func TestPivotPointsStandardSyntheticSmoke(t *testing.T) {
	indicator, _ := talive.NewPivotPoints()
	indicator.WithAnchor(talive.AnchorDaily)

	day1a := &testCandle{high: 10, low: 5, close: 7, timestamp: time.Date(2026, 5, 1, 10, 0, 0, 0, time.UTC)}
	day1b := &testCandle{high: 12, low: 4, close: 11, timestamp: time.Date(2026, 5, 1, 11, 0, 0, 0, time.UTC)}
	day2a := &testCandle{high: 14, low: 9, close: 13, timestamp: time.Date(2026, 5, 2, 10, 0, 0, 0, time.UTC)}
	day2b := &testCandle{high: 15, low: 8, close: 12, timestamp: time.Date(2026, 5, 2, 11, 0, 0, 0, time.UTC)}

	got1 := cloneFloats(indicator.Next(day1a))
	got2 := cloneFloats(indicator.Next(day1b))
	got3 := cloneFloats(indicator.Next(day2a))
	got4 := cloneFloats(indicator.Next(day2b))

	wantZero := []float64{0, 0, 0, 0, 0, 0, 0}
	want := []float64{9, 14, 17, 22, 6, 1, -2}

	if !reflect.DeepEqual(got1, wantZero) || !reflect.DeepEqual(got2, wantZero) {
		t.Fatalf("expected first period to stay idle, got %v and %v", got1, got2)
	}
	if !reflect.DeepEqual(got3, want) || !reflect.DeepEqual(got4, want) {
		t.Fatalf("unexpected pivot levels %v %v, expected %v", got3, got4, want)
	}
}

func TestPivotPointsReset(t *testing.T) {
	// Reset before any data is a no-op — indicator stays idle.
	idleIndicator, _ := talive.NewPivotPoints()
	idleIndicator.Reset()
	if !idleIndicator.IsIdle() {
		t.Fatal("Reset before any candle should leave indicator idle")
	}

	// Reset mid-period acts as a manual anchor flip: window is promoted
	// to published levels, indicator exits idle, hasLevels stays set.
	indicator, _ := talive.NewPivotPoints()
	indicator.WithAnchor(talive.AnchorDaily)
	indicator.Next(&testCandle{high: 10, low: 5, close: 7, timestamp: time.Date(2026, 5, 1, 10, 0, 0, 0, time.UTC)})
	indicator.Next(&testCandle{high: 12, low: 4, close: 11, timestamp: time.Date(2026, 5, 1, 11, 0, 0, 0, time.UTC)})
	// Window now holds aggregated day-1: H=12, L=4, C=11.

	indicator.Reset()

	if indicator.IsIdle() {
		t.Fatal("Reset after a window was built should publish levels and exit idle")
	}
	// Expected pivots for H=12, L=4, C=11 (same math as the synthetic smoke test).
	want := []float64{9, 14, 17, 22, 6, 1, -2}
	peek := indicator.Current(&testCandle{high: 1, low: 1, close: 1, timestamp: time.Date(2026, 5, 1, 12, 0, 0, 0, time.UTC)})
	if !reflect.DeepEqual(peek, want) {
		t.Fatalf("post-Reset levels = %v, want %v", peek, want)
	}
}

func Benchmark_PivotPoints_Init_Allocations(b *testing.B) {
	b.Run("PivotPoints(Standard,Daily)", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			benchSink, _ = talive.NewPivotPoints()
		}
	})
	b.Run("PivotPoints(Fibonacci,Weekly)", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			pp, _ := talive.NewPivotPoints()
			pp.WithAnchor(talive.AnchorWeekly).WithType(talive.PivotFibonacci)
			benchSink = pp
		}
	})
	b.Run("PivotPoints(Camarilla,Monthly)", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			pp, _ := talive.NewPivotPoints()
			pp.WithAnchor(talive.AnchorMonthly).WithType(talive.PivotCamarilla)
			benchSink = pp
		}
	})
}

func Benchmark_PivotPoints_Next_Allocations(b *testing.B) {
	candles, _ := readCandles("test_data/input_data2.csv")
	dataLen := len(candles)
	b.Run("PivotPoints(Standard,Daily)", func(b *testing.B) {
		indicator, _ := talive.NewPivotPoints()
		dataIndex := 0
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			dataIndex = limitedDataIndex(dataIndex, dataLen)
			sliceDummy = indicator.Next(candles[dataIndex])
		}
	})
	b.Run("PivotPoints(Fibonacci,Weekly)", func(b *testing.B) {
		indicator, _ := talive.NewPivotPoints()
		indicator.WithAnchor(talive.AnchorWeekly).WithType(talive.PivotFibonacci)
		dataIndex := 0
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			dataIndex = limitedDataIndex(dataIndex, dataLen)
			sliceDummy = indicator.Next(candles[dataIndex])
		}
	})
	b.Run("PivotPoints(Camarilla,Monthly)", func(b *testing.B) {
		indicator, _ := talive.NewPivotPoints()
		indicator.WithAnchor(talive.AnchorMonthly).WithType(talive.PivotCamarilla)
		dataIndex := 0
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			dataIndex = limitedDataIndex(dataIndex, dataLen)
			sliceDummy = indicator.Next(candles[dataIndex])
		}
	})
}

func Benchmark_PivotPoints_Current_Allocations(b *testing.B) {
	candles, _ := readCandles("test_data/input_data2.csv")
	dataLen := len(candles)
	b.Run("PivotPoints(Standard,Daily)", func(b *testing.B) {
		indicator, _ := talive.NewPivotPoints()
		dataIndex := primeForCurrentBench(indicator, candles)
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			dataIndex = limitedDataIndex(dataIndex, dataLen)
			sliceDummy = indicator.Current(candles[dataIndex])
		}
	})
	b.Run("PivotPoints(Fibonacci,Weekly)", func(b *testing.B) {
		indicator, _ := talive.NewPivotPoints()
		indicator.WithAnchor(talive.AnchorWeekly).WithType(talive.PivotFibonacci)
		dataIndex := primeForCurrentBench(indicator, candles)
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			dataIndex = limitedDataIndex(dataIndex, dataLen)
			sliceDummy = indicator.Current(candles[dataIndex])
		}
	})
	b.Run("PivotPoints(Camarilla,Monthly)", func(b *testing.B) {
		indicator, _ := talive.NewPivotPoints()
		indicator.WithAnchor(talive.AnchorMonthly).WithType(talive.PivotCamarilla)
		dataIndex := primeForCurrentBench(indicator, candles)
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			dataIndex = limitedDataIndex(dataIndex, dataLen)
			sliceDummy = indicator.Current(candles[dataIndex])
		}
	})
}
