package talive_test

import (
	"reflect"
	"testing"

	"github.com/MoroZvlg/talive"
)

// NOTE: The CSV fixtures consumed by these tests (test_data/zigzag/output_*.csv) were generated by
// streaming input_data2.csv through python talipp.ZigZag and reshaping its sparse-pivot output \
// into the per-bar 3-slot layout. See scripts/zigzag_oracle.py.

func TestZigZagDefault(t *testing.T) {
	candles, _ := readCandles("test_data/input_data2.csv")
	expected, _ := readData("test_data/zigzag/output_default.csv", []int{1, 2, 3}, 7)
	indicator, _ := talive.NewZigZag(0.05, 5)
	got := [][]float64{
		make([]float64, len(candles)),
		make([]float64, len(candles)),
		make([]float64, len(candles)),
	}
	for i, candle := range candles {
		res := indicator.Next(candle)
		got[0][i] = roundFloat(res[0], 7)
		got[1][i] = roundFloat(res[1], 7)
		got[2][i] = roundFloat(res[2], 7)
	}
	if !reflect.DeepEqual(got[0], expected[0]) {
		t.Fatal(`[ZigZag(0.05,5)] LastHigh values didn't match `, difference(got[0], expected[0]))
	}
	if !reflect.DeepEqual(got[1], expected[1]) {
		t.Fatal(`[ZigZag(0.05,5)] LastLow values didn't match `, difference(got[1], expected[1]))
	}
	if !reflect.DeepEqual(got[2], expected[2]) {
		t.Fatal(`[ZigZag(0.05,5)] Event values didn't match `, difference(got[2], expected[2]))
	}
}

func TestZigZagMin(t *testing.T) {
	candles, _ := readCandles("test_data/input_data2.csv")
	expected, _ := readData("test_data/zigzag/output_min.csv", []int{1, 2, 3}, 7)
	indicator, _ := talive.NewZigZag(0.01, 1)
	got := [][]float64{
		make([]float64, len(candles)),
		make([]float64, len(candles)),
		make([]float64, len(candles)),
	}
	for i, candle := range candles {
		res := indicator.Next(candle)
		got[0][i] = roundFloat(res[0], 7)
		got[1][i] = roundFloat(res[1], 7)
		got[2][i] = roundFloat(res[2], 7)
	}
	if !reflect.DeepEqual(got[0], expected[0]) {
		t.Fatal(`[ZigZag(0.01,1)] LastHigh values didn't match `, difference(got[0], expected[0]))
	}
	if !reflect.DeepEqual(got[1], expected[1]) {
		t.Fatal(`[ZigZag(0.01,1)] LastLow values didn't match `, difference(got[1], expected[1]))
	}
	if !reflect.DeepEqual(got[2], expected[2]) {
		t.Fatal(`[ZigZag(0.01,1)] Event values didn't match `, difference(got[2], expected[2]))
	}
}

func TestZigZagMax(t *testing.T) {
	candles, _ := readCandles("test_data/input_data2.csv")
	expected, _ := readData("test_data/zigzag/output_max.csv", []int{1, 2, 3}, 7)
	indicator, _ := talive.NewZigZag(0.10, 20)
	got := [][]float64{
		make([]float64, len(candles)),
		make([]float64, len(candles)),
		make([]float64, len(candles)),
	}
	for i, candle := range candles {
		res := indicator.Next(candle)
		got[0][i] = roundFloat(res[0], 7)
		got[1][i] = roundFloat(res[1], 7)
		got[2][i] = roundFloat(res[2], 7)
	}
	if !reflect.DeepEqual(got[0], expected[0]) {
		t.Fatal(`[ZigZag(0.10,20)] LastHigh values didn't match `, difference(got[0], expected[0]))
	}
	if !reflect.DeepEqual(got[1], expected[1]) {
		t.Fatal(`[ZigZag(0.10,20)] LastLow values didn't match `, difference(got[1], expected[1]))
	}
	if !reflect.DeepEqual(got[2], expected[2]) {
		t.Fatal(`[ZigZag(0.10,20)] Event values didn't match `, difference(got[2], expected[2]))
	}
}

func TestZigZagIdle(t *testing.T) {
	z, _ := talive.NewZigZag(0.05, 1)

	out := z.Next(&testCandle{high: 100, low: 100, close: 100})
	if !z.IsIdle() {
		t.Fatal(`[ZigZag(0.05,1)] expected idle after seed candle`)
	}
	if out[0] != 0 || out[1] != 0 || out[2] != 0 {
		t.Fatalf(`[ZigZag(0.05,1)] expected [0,0,0] during idle, got %v`, out)
	}

	out = z.Next(&testCandle{high: 106, low: 100, close: 106})
	if z.IsIdle() {
		t.Fatal(`[ZigZag(0.05,1)] expected not idle after first lock`)
	}
	if out[0] != 0 || out[1] != 100 || out[2] != -1 {
		t.Fatalf(`[ZigZag(0.05,1)] expected [0,100,-1] after first LOW lock, got %v`, out)
	}
}

func TestZigZagCurrentVal(t *testing.T) {
	candles, _ := readCandles("test_data/input_data2.csv")
	expected, _ := readData("test_data/zigzag/output_default.csv", []int{1, 2, 3}, 8)
	indicator, _ := talive.NewZigZag(0.05, 5)

	const peekIdx = 50
	for i := 0; i < peekIdx; i++ {
		indicator.Next(candles[i])
	}

	curr := indicator.Current(candles[peekIdx])
	expHigh := expected[0][peekIdx]
	expLow := expected[1][peekIdx]
	expEvent := expected[2][peekIdx]
	if roundFloat(curr[0], 8) != roundFloat(expHigh, 8) {
		t.Fatalf(`[ZigZag(0.05,5)] Current LastHigh = %f, expected %f`, curr[0], expHigh)
	}
	if roundFloat(curr[1], 8) != roundFloat(expLow, 8) {
		t.Fatalf(`[ZigZag(0.05,5)] Current LastLow = %f, expected %f`, curr[1], expLow)
	}
	if roundFloat(curr[2], 8) != roundFloat(expEvent, 8) {
		t.Fatalf(`[ZigZag(0.05,5)] Current Event = %f, expected %f`, curr[2], expEvent)
	}

	next := indicator.Next(candles[peekIdx])
	if roundFloat(next[0], 8) != roundFloat(expHigh, 8) {
		t.Fatalf(`[ZigZag(0.05,5)] Current call broke Next LastHigh: got %f, expected %f`, next[0], expHigh)
	}
	if roundFloat(next[1], 8) != roundFloat(expLow, 8) {
		t.Fatalf(`[ZigZag(0.05,5)] Current call broke Next LastLow: got %f, expected %f`, next[1], expLow)
	}
	if roundFloat(next[2], 8) != roundFloat(expEvent, 8) {
		t.Fatalf(`[ZigZag(0.05,5)] Current call broke Next Event: got %f, expected %f`, next[2], expEvent)
	}
}

func Benchmark_ZigZag_Init_Allocations(b *testing.B) {
	b.Run("ZigZag(0.05,5)", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			benchSink, _ = talive.NewZigZag(0.05, 5)
		}
	})
	b.Run("ZigZag(0.10,20)", func(b *testing.B) {
		for i := 0; i < b.N; i++ {
			benchSink, _ = talive.NewZigZag(0.10, 20)
		}
	})
}

func Benchmark_ZigZag_Next_Allocations(b *testing.B) {
	candles, _ := readCandles("test_data/input_data2.csv")
	dataLen := len(candles)
	b.Run("ZigZag(0.05,5)", func(b *testing.B) {
		indicator, _ := talive.NewZigZag(0.05, 5)
		dataIndex := 0
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			dataIndex = limitedDataIndex(dataIndex, dataLen)
			sliceDummy = indicator.Next(candles[dataIndex])
		}
	})
	b.Run("ZigZag(0.10,20)", func(b *testing.B) {
		indicator, _ := talive.NewZigZag(0.10, 20)
		dataIndex := 0
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			dataIndex = limitedDataIndex(dataIndex, dataLen)
			sliceDummy = indicator.Next(candles[dataIndex])
		}
	})
}

func Benchmark_ZigZag_Current_Allocations(b *testing.B) {
	candles, _ := readCandles("test_data/input_data2.csv")
	dataLen := len(candles)
	b.Run("ZigZag(0.05,5)", func(b *testing.B) {
		indicator, _ := talive.NewZigZag(0.05, 5)
		dataIndex := primeForCurrentBench(indicator, candles)
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			dataIndex = limitedDataIndex(dataIndex, dataLen)
			sliceDummy = indicator.Current(candles[dataIndex])
		}
	})
	b.Run("ZigZag(0.10,20)", func(b *testing.B) {
		indicator, _ := talive.NewZigZag(0.10, 20)
		dataIndex := primeForCurrentBench(indicator, candles)
		b.ResetTimer()
		for i := 0; i < b.N; i++ {
			dataIndex = limitedDataIndex(dataIndex, dataLen)
			sliceDummy = indicator.Current(candles[dataIndex])
		}
	})
}
